# Config file for automatic testing at travis-ci.org

language: python

python:
  # - "3.7-dev"
  - "3.6"
  - "3.5"
  # - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r example/requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - python setup.py test

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov

env:
  - DEVELOPMENT=false
